# Generated by Django 5.0 on 2024-01-01 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Department Name')),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(auto_now=True)),
                ('requested_by', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bank_name', models.CharField(max_length=50)),
                ('account_no', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=50)),
                ('bank_receipt_no', models.CharField(max_length=50)),
                ('amount_banked', models.IntegerField()),
                ('curency', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
                ('banked_by', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='noah.department')),
            ],
            options={
                'verbose_name': 'Banking',
                'verbose_name_plural': 'Bankings',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(auto_now=True)),
                ('purpose', models.CharField(max_length=50)),
                ('amount_recieved', models.IntegerField()),
                ('spent_by', models.CharField(max_length=50)),
                ('date_recieved', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noah.department', verbose_name='department')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.CreateModel(
            name='Exp_break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.CharField(max_length=50)),
                ('rate', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noah.expenses', verbose_name='expense')),
            ],
            options={
                'verbose_name': 'Exp_break',
                'verbose_name_plural': 'Exp_breaks',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paid', models.DateField(auto_now=True)),
                ('receipt_no', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('payment_purpose', models.CharField(max_length=50)),
                ('amount_paid', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Department', to='noah.department')),
                ('recieved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Request_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noah.request', verbose_name='request')),
            ],
            options={
                'verbose_name': 'Request_item',
                'verbose_name_plural': 'Request_items',
            },
        ),
    ]
